#!/bin/bash

# Script to add DeepSeek integration files to Xcode project
# Run this script from the project root directory

echo "🎨 Adding DeepSeek Integration Files to Xcode Project"
echo ""
echo "This script will help you add the new files to your Xcode project."
echo ""
echo "📝 New Files to Add:"
echo "  - Project_Color/Config/APIConfig.swift"
echo "  - Project_Color/Config/Secrets.xcconfig"
echo "  - Project_Color/Services/AI/DeepSeekService.swift"
echo "  - Project_Color/Services/AI/ColorAnalysisEvaluator.swift"
echo ""
echo "📖 Instructions:"
echo ""
echo "1. Open Project_Color.xcodeproj in Xcode"
echo ""
echo "2. Create AI folder in Services group:"
echo "   - Right-click on 'Services' folder in Project Navigator"
echo "   - Select 'New Group'"
echo "   - Name it 'AI'"
echo ""
echo "3. Add AI service files:"
echo "   - Right-click on 'Services/AI' group"
echo "   - Select 'Add Files to \"Project_Color\"...'"
echo "   - Navigate to Project_Color/Services/AI/"
echo "   - Select both .swift files"
echo "   - Make sure 'Copy items if needed' is UNCHECKED"
echo "   - Make sure 'Project_Color' target is CHECKED"
echo "   - Click 'Add'"
echo ""
echo "4. Add Config files:"
echo "   - Right-click on 'Config' folder in Project Navigator"
echo "   - Select 'Add Files to \"Project_Color\"...'"
echo "   - Navigate to Project_Color/Config/"
echo "   - Select APIConfig.swift"
echo "   - Make sure 'Copy items if needed' is UNCHECKED"
echo "   - Make sure 'Project_Color' target is CHECKED"
echo "   - Click 'Add'"
echo ""
echo "5. Configure API Key in Xcode:"
echo "   - Select the project (top of navigator)"
echo "   - Select 'Project_Color' target"
echo "   - Go to 'Build Settings' tab"
echo "   - Click '+' button at the top"
echo "   - Select 'Add User-Defined Setting'"
echo "   - Name: DEEPSEEK_API_KEY"
echo "   - Value: sk-02551e4b861b4d7abb754abef5d73ae5"
echo ""
echo "6. Update Info.plist (if needed):"
echo "   - The Info.plist has already been updated with DEEPSEEK_API_KEY"
echo "   - Just verify it's there in Xcode"
echo ""
echo "7. Build and Test:"
echo "   - Press Cmd+B to build"
echo "   - Fix any compilation errors (should be none)"
echo "   - Run the app and test the AI evaluation feature"
echo ""
echo "✅ Done! The AI evaluation should now work automatically after analysis."
echo ""
echo "📚 For more information, see:"
echo "   - Project_Color/Config/README.md"
echo "   - DeepSeek_Integration_Summary.md"

