#!/bin/bash

# 添加 Garden Weather 相关文件到 Xcode 项目的脚本

echo "🌸 Garden Weather 文件添加指南"
echo "================================"
echo ""
echo "新创建的文件："
echo "  1. Project_Color/Services/LocationWeatherService.swift"
echo "  2. Project_Color/Views/GardenView.swift"
echo ""
echo "⚠️  这些文件需要手动添加到 Xcode 项目中"
echo ""
echo "📝 操作步骤："
echo ""
echo "1. 打开 Xcode 项目："
echo "   open Project_Color.xcodeproj"
echo ""
echo "2. 添加 LocationWeatherService.swift："
echo "   - 在左侧导航器中找到 'Project_Color/Services' 文件夹"
echo "   - 右键点击 'Services' 文件夹"
echo "   - 选择 'Add Files to \"Project_Color\"...'"
echo "   - 找到并选择 'LocationWeatherService.swift'"
echo "   - 确保勾选 'Copy items if needed' 和 'Add to targets: Project_Color'"
echo "   - 点击 'Add'"
echo ""
echo "3. 添加 GardenView.swift："
echo "   - 在左侧导航器中找到 'Project_Color/Views' 文件夹"
echo "   - 右键点击 'Views' 文件夹"
echo "   - 选择 'Add Files to \"Project_Color\"...'"
echo "   - 找到并选择 'GardenView.swift'"
echo "   - 确保勾选 'Copy items if needed' 和 'Add to targets: Project_Color'"
echo "   - 点击 'Add'"
echo ""
echo "4. 启用 WeatherKit Capability："
echo "   - 选择项目根节点（Project_Color）"
echo "   - 选择 Target: Project_Color"
echo "   - 切换到 'Signing & Capabilities' 标签"
echo "   - 点击 '+ Capability' 按钮"
echo "   - 搜索并添加 'WeatherKit'"
echo ""
echo "5. 构建并运行："
echo "   - 按 Cmd + B 构建项目"
echo "   - 按 Cmd + R 运行到设备或模拟器"
echo ""
echo "✅ 完成后，garden 模式将支持天气信息显示！"
echo ""

